VMSApp/VMSApp/Controllers/SequerityController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using VMSApp.Models;

namespace VMSApp.Controllers
{
    public class SequerityController : Controller
    {
        // GET: Sequerity


        private readonly ILogger<SequerityController> _logger;

        public SequerityController(ILogger<SequerityController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        // GET: Sequerity/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Sequerity/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sequerity/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Sequerity/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        public ActionResult Signup(Visitor visitor)
        {
            VisitorDbManager.Insert(visitor);

            return View();
        }


        public ActionResult Created()
        {
            return Ok(new { message = "Visitor created" });
        }

        public ActionResult UpdateVisitor()
        {
            return View();
        }
        public ActionResult InVisitor()

        {
            List<Visitor> allvisitor = VisitorDbManager.GetAllVisitorIn();
            this.ViewData["allvisitor"] = allvisitor;
            return View();
        }
        public ActionResult OutVisitor()
        {
            return View();
        }





        // POST: Sequerity/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Sequerity/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Sequerity/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

VMSApp/VMSApp/Views/Sequerity/Created.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

VMSApp/VMSApp/Views/Sequerity/InVisitor.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewData["Title"] = "Products Gallery Page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.5.2/dist/css/bootstrap.min.css" rel="stylesheet" />
    <style>
        table {
            border:solid 2px ;

        }
         th{
            color:red ;
            margin:10px;
            border:solid 1px;
            background-color:green;
       
            
        }
       td {
            color:black;
            margin:10px;
            border: solid 1px;
        }


        
    </style>
</head>
<body>

    <h1>AllVisitor</h1>
    <hr />
    <div class="text-center">
        @{
            List<Visitor> inVisitor = (List<Visitor>)ViewData["allvisitor"];
            int count = 0;
            <table class="tables">
                <tr >
                     <th>Count</th>
                     <th>ID</th>
                    <th>AdharNO</th>
                    <th>FirstName</th>
                    <th>LastName</th>
                    <th>Delete</th>
                    <th>update</th>
                    
                </tr>

                @foreach (Visitor visit in inVisitor)
                {      
                    int count2 = count + 1;
                    count++;
                    <tr>
                       <td>@count2</td>
                       <td>@visit.Id</td>
                        <td>@visit.AdharNo</td>
                        <td>@visit.FirstName</td>
                        <td>@visit.LastName</td>
                        <td>
                          <li href="delete/{id}">Delete</li>
                          </td>
                    </tr>




                }
            </table>
        }
        <hr />
    </div>
</body>
</html>

VMSApp/VMSApp/Views/Sequerity/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sequerity" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Sequerity" asp-action="Signup">Signup Visitor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sequerity" asp-action="UpdateVisitor">Update Visitor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sequerity" asp-action="InVisitor">In Visitor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sequerity" asp-action="OutVisitor">Out Visitor</a>
                        </li>
                    </ul>
                </div>



</body>
</html>

VMSApp/VMSApp/Views/Sequerity/OutVisitor.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

VMSApp/VMSApp/Views/Sequerity/Signup.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    .input_box {
        position: relative;
        margin-top: 30px;
        margin-bottom: 10px;
        width: 100%;
        height: 40px;
    }

        .input_box input {
            height: 100%;
            width: 100%;
            border: 1.5px solid black;
            outline: none;
            padding: 0 30px;
            color: #333;
            transition: all 0.2s ease;
            border-bottom: 1.5px solid #aaaaaa;
        }

        .input_box select {
            height: 100%;
            width: 100%;
            border: 1.5px solid black;
            outline: none;
            padding: 0 30px;
            color: #333;
            transition: all 0.2s ease;
            border-bottom: 1.5px solid #aaaaaa;
        }

        .input_box input:focus {
            border-color: #7d2ae8;
        }

    .signup_form {
        border: 1px solid #aaaaaa;
        margin: 20px
    }

    .container {
        border: 1.5px solid black
    }
</style>
<body>
      
    <div  class=""> 
        <h1>SignUp</h1>
        <div class="">
            <form   method="post">
        <div class="input_box">
           <label for="adharno">Adharno:</label>
          <input type="text" id="adharno" name="adharno" required>
        </div>

        <div class="input_box">
            <label for="firstname">Firstname:</label>
            <input type="text" id="firstname" name="firstname" required>
        </div>

        <div class="input_box">
            <label for="lastname">Lastname:</label>
            <input type="text" id="lastname" name="lastname" required>
        </div>
                <div class="input_box">
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email" required>
                </div>
                <div class="input_box">
                    <label for="admin">Admin:</label>
                    <input type="text" id="admin" name="admin" required>
                </div>
                <div class="input_box">
                    <label for="noofvisitor">noof visitor:</label>
                    <input type="number" id="noofvisitor" name="noofvisitor" required>
                </div>
                <div class="input_box">
                    <label for="reason">Reason:</label>

                    <textarea for="reason" id="reason" name="reason"></textarea>
                </div>

                <div class="input_box">
                    <label for="vdate">Date:</label>
                    <input type="date" id="date" name="date" required>
                </div>
                <div class="input_box">
                    <label for="time">Time:</label>
                    <input type="time" id="time" name="time" required>
                </div >
              


                <div class="input_box"> <input type="submit" value="Sign Up"  style="background-color:green;color:black" ></div>
        <div>
         </div>
    </form>
            <li >
                <a class="nav-item" asp-area="" asp-controller="Sequerity" asp-action="Index">Sequerity Page</a>
            </li>
            <li>
                <a class="nav-item" asp-area="" asp-controller="Home" asp-action="Index">Log Out</a>
            </li>



        </div>
    </div>

</body>
</html>

VMSApp/VMSApp/Views/Sequerity/UpdateVisitor.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}